### ISSUE TITLE
Allow "Constraints" and "Required" to reference relative data elements

### ISSUE THREAD

**Issue by nealkruis** [bigladder/lattice#48]
Constraints: This is the case if we want to constraint the value (or other attributes?) of the data element referenced in a group. See climate information time series instances.

Required: If something depends on the value of a data_element relative to this one. e.g. for draft Unitary RS changes:

```yaml
unitary:
    performance:
        indoor_fan_representation:
            operation_speed_control_type: DISCRETE # or CONTINUOUS
        dx_system_representation:
        compressor_and_fan_control_sequence:
            fan_speed_number: # Required: "if ..indoor_fan_representation.operation_speed_control_type = DISCRETE"
            air_volumetric_flow_rate: # Required: "if ..indoor_fan_representation.operation_speed_control_type = CONTINUOUS"        
 ```
