### ISSUE TITLE
Warnings generated from incomplete logic implementation

### ISSUE THREAD

**Issue by spahrenk** [bigladder/lattice#90]
Inline logic, as shown below, generates as "true" in the source code.
```
absolute_temperature:
   Required: "if !differential_temperature"
...

differential_temperature:
   Required: "if !absolute_temperature"
```

This triggers the check in `load-object.h`
```
if (required)
{
    logger->send_warning(ex.what());
}
```
As a result, many warnings are generated in cse reports such as 
```
???     COMMANDS.CSE(1567): Warning: DHWHeater 'HPWH' of DHWSYS 'DS1': 
???         [json.exception.out_of_range.403] key 'absolute_temperature' not found
```
These cause diffs and are not very helpful in this context.

These end up echoed to `cse` reports. Is it possible to suppress the warnings until the inline logic is implemented?
